2022/08/21 18:43:49 [error] 7#7: *6 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:05:57 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:05:59 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:06:01 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:06:03 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:06:09 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:06:18 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:06:46 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:09:51 [crit] 7#7: *10 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/21 19:09:51 [error] 7#7: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:09:55 [error] 7#7: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:10:23 [error] 7#7: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams"
2022/08/21 19:10:41 [error] 7#7: *19 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/21 19:37:03 [error] 7#7: *22 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/21 19:37:06 [error] 7#7: *22 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/21 19:37:49 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/21 19:37:53 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/21 19:37:55 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/21 19:37:57 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/21 19:40:28 [error] 8#8: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/21 19:46:51 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/21 19:47:58 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/22 05:24:37 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "gfcams.test.ru"
2022/08/23 18:26:14 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:15:31 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:22:29 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:29:34 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:40:34 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:40:36 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru", referrer: "https://gfcams.test.ru/"
2022/08/23 19:40:36 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru", referrer: "https://gfcams.test.ru/"
2022/08/23 19:41:02 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:41:04 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru", referrer: "https://gfcams.test.ru/"
2022/08/23 19:41:08 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:42:51 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:46:12 [error] 7#7: *14 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:47:48 [error] 7#7: *14 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru"
2022/08/23 19:47:49 [error] 7#7: *14 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru", referrer: "https://gfcams.test.ru/"
2022/08/23 19:47:49 [error] 7#7: *14 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams.test.ru", referrer: "https://gfcams.test.ru/"
2022/08/23 19:48:32 [error] 7#7: *20 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/23 19:48:33 [error] 7#7: *20 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/23 19:48:33 [error] 7#7: *20 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/23 19:50:39 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/23 19:50:41 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/23 19:50:41 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/23 19:52:19 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/23 19:52:21 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/23 19:52:21 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/24 05:03:40 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/24 05:03:42 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/24 05:03:42 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/24 05:03:50 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/24 05:03:52 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/24 05:35:16 [error] 7#7: *10 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/24 05:35:18 [error] 7#7: *10 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/24 17:52:37 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/24 18:05:22 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/24 18:05:23 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/24 18:05:23 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/24 18:05:43 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/24 18:05:45 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/24 19:10:06 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/24 19:10:08 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/24 19:10:08 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/25 05:55:47 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams"
2022/08/25 05:55:49 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/08/25 05:55:49 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.19.0.6:9000", host: "gfcams", referrer: "https://gfcams/"
2022/09/11 16:46:32 [error] 7#7: *70 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: gfcams, request: "GET /memcached HTTP/2.0", upstream: "fastcgi://172.19.0.7:9000", host: "gfcams"
2022/09/11 17:34:19 [crit] 7#7: *110 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/09/11 17:34:19 [crit] 7#7: *111 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/09/11 19:04:08 [crit] 7#7: *138 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/09/11 19:04:08 [crit] 7#7: *139 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/09/12 05:48:24 [crit] 7#7: *200 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/09/12 05:48:24 [crit] 7#7: *201 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/09/12 06:21:59 [crit] 7#7: *235 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/09/12 18:03:30 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.8:9001", host: "gfcams"
2022/09/12 18:03:47 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.8:9001", host: "gfcams"
2022/09/12 18:22:20 [error] 7#7: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.8:9001", host: "gfcams"
2022/09/12 18:23:12 [error] 7#7: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.8:9001", host: "gfcams"
2022/09/12 18:24:42 [error] 7#7: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.8:9001", host: "gfcams"
2022/09/12 18:24:46 [error] 7#7: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.8:9001", host: "gfcams"
2022/09/13 08:50:08 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9004", host: "gfcams"
2022/09/13 08:50:08 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9001", host: "gfcams"
2022/09/13 08:50:08 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9002", host: "gfcams"
2022/09/13 08:50:08 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "gfcams"
2022/09/13 08:50:10 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9001", host: "gfcams"
2022/09/13 08:50:10 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9004", host: "gfcams"
2022/09/13 08:50:10 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:50:12 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9004", host: "gfcams"
2022/09/13 08:50:12 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:51:03 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9004", host: "gfcams"
2022/09/13 08:51:03 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "gfcams"
2022/09/13 08:51:03 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9002", host: "gfcams"
2022/09/13 08:51:03 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9001", host: "gfcams"
2022/09/13 08:51:06 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9004", host: "gfcams"
2022/09/13 08:51:06 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:51:09 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9001", host: "gfcams"
2022/09/13 08:51:09 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:51:11 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "gfcams"
2022/09/13 08:51:11 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9004", host: "gfcams"
2022/09/13 08:51:11 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9002", host: "gfcams"
2022/09/13 08:51:11 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:51:15 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9004", host: "gfcams"
2022/09/13 08:51:15 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9001", host: "gfcams"
2022/09/13 08:51:15 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:51:17 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:54:29 [crit] 7#7: *27 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.21.0.1, server: 0.0.0.0:443
2022/09/13 08:54:29 [error] 7#7: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9004", host: "gfcams"
2022/09/13 08:54:29 [error] 7#7: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "gfcams"
2022/09/13 08:54:29 [error] 7#7: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9002", host: "gfcams"
2022/09/13 08:54:29 [error] 7#7: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9001", host: "gfcams"
2022/09/13 08:55:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "gfcams"
2022/09/13 08:55:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9001", host: "gfcams"
2022/09/13 08:55:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9002", host: "gfcams"
2022/09/13 08:55:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9005", host: "gfcams"
2022/09/13 08:55:43 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9001", host: "gfcams"
2022/09/13 08:55:43 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "gfcams"
2022/09/13 08:55:43 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:55:45 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "gfcams"
2022/09/13 08:55:45 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:55:46 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "gfcams"
2022/09/13 08:55:46 [error] 7#7: *2 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:59:44 [crit] 7#7: *24 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.21.0.1, server: 0.0.0.0:443
2022/09/13 08:59:44 [crit] 7#7: *25 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.21.0.1, server: 0.0.0.0:443
2022/09/13 08:59:44 [error] 7#7: *26 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:59:46 [error] 7#7: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "gfcams"
2022/09/13 08:59:46 [error] 7#7: *26 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 08:59:47 [error] 7#7: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9001", host: "gfcams"
2022/09/13 08:59:47 [error] 7#7: *26 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 10:42:58 [error] 7#7: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "gfcams"
2022/09/13 10:42:58 [error] 7#7: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9005", host: "gfcams"
2022/09/13 10:42:58 [error] 7#7: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9002", host: "gfcams"
2022/09/13 10:42:58 [error] 7#7: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9001", host: "gfcams"
2022/09/13 10:43:00 [error] 7#7: *30 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 10:43:02 [error] 7#7: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "gfcams"
2022/09/13 10:43:02 [error] 7#7: *30 no live upstreams while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "gfcams"
2022/09/13 11:10:08 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: gfcams, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.21.0.10:9001", host: "gfcams", referrer: "https://gfcams/"
