2022/07/30 13:28:56 [crit] 7#7: *7 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:28:56 [error] 7#7: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:29:14 [crit] 7#7: *7 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:29:14 [error] 7#7: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:32:17 [crit] 7#7: *3 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:32:17 [error] 7#7: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:33:08 [crit] 7#7: *3 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:33:08 [error] 7#7: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:37:28 [crit] 8#8: *3 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:37:28 [error] 8#8: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:37:29 [crit] 8#8: *3 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:37:29 [error] 8#8: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:37:30 [crit] 8#8: *3 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:37:30 [error] 8#8: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:37:30 [crit] 8#8: *3 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:37:30 [error] 8#8: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: ralzo, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:38:20 [crit] 8#8: *3 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:38:20 [error] 8#8: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:38:22 [crit] 8#8: *5 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.20.0.1, server: 0.0.0.0:443
2022/07/30 13:38:22 [crit] 8#8: *6 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.20.0.1, server: 0.0.0.0:443
2022/07/30 13:38:22 [crit] 8#8: *7 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:38:22 [error] 8#8: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:39:01 [crit] 8#8: *7 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:39:01 [error] 8#8: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 13:39:09 [crit] 8#8: *7 realpath() "/ralzo/public" failed (2: No such file or directory), client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", host: "vk.localhost"
2022/07/30 13:39:09 [error] 8#8: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 14:13:04 [crit] 7#7: *5 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.20.0.1, server: 0.0.0.0:443
2022/07/30 14:13:04 [crit] 7#7: *6 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.20.0.1, server: 0.0.0.0:443
2022/07/30 15:30:33 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 15:30:54 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 15:31:18 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /hello HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 15:31:34 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /hello HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 16:09:40 [error] 7#7: *16 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /hello HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 16:09:57 [error] 7#7: *16 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /test HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 16:10:15 [error] 7#7: *16 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /test HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 16:55:57 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 16:58:39 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 16:59:18 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:00:18 [error] 7#7: *25 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:21:07 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:21:16 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:22:59 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:23:18 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:23:52 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:23:52 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:24:06 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:24:06 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:24:17 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:24:17 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:24:29 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:24:29 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost", referrer: "https://vk.localhost/news"
2022/07/30 17:26:26 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:26:27 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:28:15 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:28:32 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:28:49 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:28:49 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:29:01 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:29:01 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:30:28 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:32:36 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:32:44 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:32:49 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:38:48 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:38:48 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/2 HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:38:54 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:38:54 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:43:41 [crit] 7#7: *58 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.20.0.1, server: 0.0.0.0:443
2022/07/30 17:43:41 [crit] 7#7: *59 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.20.0.1, server: 0.0.0.0:443
2022/07/30 17:43:44 [error] 7#7: *60 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:43:44 [error] 7#7: *60 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:44:01 [error] 7#7: *60 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:45:15 [error] 7#7: *60 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:45:28 [error] 7#7: *60 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:46:01 [error] 7#7: *60 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:46:19 [error] 7#7: *60 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:46:20 [error] 7#7: *60 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.20.0.1, server: vk, request: "GET /news/card/fsadf HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
2022/07/30 17:55:20 [error] 7#7: *68 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.20.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.20.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.20.0.5:9000", host: "vk.localhost"
