2022/09/12 20:09:19 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: 2022-09-12T23:09:19+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9000", host: "symfony"
2022/09/12 20:11:19 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: 2022-09-12T23:11:19+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:12:20 [error] 7#7: *6 FastCGI sent in stderr: "PHP message: 2022-09-12T23:12:20+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:12:24 [error] 7#7: *6 FastCGI sent in stderr: "PHP message: 2022-09-12T23:12:24+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:17:48 [error] 7#7: *10 FastCGI sent in stderr: "PHP message: 2022-09-12T23:17:48+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:17:50 [error] 7#7: *10 FastCGI sent in stderr: "PHP message: 2022-09-12T23:17:50+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:17:53 [error] 7#7: *10 FastCGI sent in stderr: "PHP message: 2022-09-12T23:17:53+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:25:43 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: 2022-09-12T23:25:43+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:28:02 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: 2022-09-12T23:28:02+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:28:05 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: 2022-09-12T23:28:05+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:31:31 [error] 7#7: *16 FastCGI sent in stderr: "PHP message: 2022-09-12T23:31:31+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:41:46 [crit] 7#7: *23 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.21.0.1, server: 0.0.0.0:443
2022/09/12 20:41:46 [crit] 7#7: *24 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.21.0.1, server: 0.0.0.0:443
2022/09/13 08:51:20 [error] 7#7: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9004", host: "symfony"
2022/09/13 08:51:20 [error] 7#7: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "symfony"
2022/09/13 08:51:20 [error] 7#7: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9002", host: "symfony"
2022/09/13 08:51:20 [error] 7#7: *22 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "symfony"
2022/09/13 08:51:22 [error] 7#7: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9001", host: "symfony"
2022/09/13 08:51:22 [error] 7#7: *22 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "symfony"
2022/09/13 08:55:48 [error] 7#7: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "symfony"
2022/09/13 08:55:48 [error] 7#7: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9005", host: "symfony"
2022/09/13 08:55:48 [error] 7#7: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9002", host: "symfony"
2022/09/13 08:55:48 [error] 7#7: *12 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "symfony"
2022/09/13 08:55:49 [error] 7#7: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.10:9001", host: "symfony", referrer: "https://symfony/"
2022/09/13 08:55:49 [error] 7#7: *12 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://highload", host: "symfony", referrer: "https://symfony/"
2022/09/13 08:59:41 [crit] 7#7: *17 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.21.0.1, server: 0.0.0.0:443
2022/09/13 08:59:41 [crit] 7#7: *18 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.21.0.1, server: 0.0.0.0:443
2022/09/13 08:59:41 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9005", host: "symfony"
2022/09/13 08:59:41 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "symfony"
2022/09/13 08:59:41 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9002", host: "symfony"
2022/09/13 08:59:41 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9001", host: "symfony"
2022/09/13 08:59:41 [error] 7#7: *19 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://highload", host: "symfony", referrer: "https://symfony/"
2022/09/13 10:43:04 [error] 7#7: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9001", host: "symfony"
2022/09/13 10:43:04 [error] 7#7: *37 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "symfony"
2022/09/13 10:43:05 [error] 7#7: *37 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://highload", host: "symfony", referrer: "https://symfony/"
2022/09/13 10:43:06 [error] 7#7: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.13:9004", host: "symfony"
2022/09/13 10:43:06 [error] 7#7: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9005", host: "symfony"
2022/09/13 10:43:06 [error] 7#7: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.10:9002", host: "symfony"
2022/09/13 10:43:06 [error] 7#7: *37 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://highload", host: "symfony"
2022/09/13 10:43:07 [error] 7#7: *37 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://highload", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:10:17 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.16:9003", host: "symfony"
2022/09/13 11:10:17 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9004", host: "symfony"
2022/09/13 11:10:17 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.14:9005", host: "symfony"
2022/09/13 11:10:17 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.12:9006", host: "symfony"
2022/09/13 11:10:18 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.12:9006", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:10:18 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.14:9005", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:10:18 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.11:9004", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:10:18 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.16:9003", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:10:23 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.12:9006", host: "symfony"
2022/09/13 11:10:23 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.14:9005", host: "symfony"
2022/09/13 11:10:23 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9004", host: "symfony"
2022/09/13 11:10:23 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.16:9003", host: "symfony"
2022/09/13 11:10:24 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.16:9003", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:10:24 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.11:9004", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:10:24 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.14:9005", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:10:24 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.12:9006", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:10:34 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.16:9003", host: "symfony"
2022/09/13 11:10:34 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9004", host: "symfony"
2022/09/13 11:10:34 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.12:9006", host: "symfony"
2022/09/13 11:10:34 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.14:9005", host: "symfony"
2022/09/13 11:10:34 [error] 7#7: *10 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://highload-symfony", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:16:54 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.16:9004", host: "symfony"
2022/09/13 11:16:54 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "symfony"
2022/09/13 11:16:54 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.14:9006", host: "symfony"
2022/09/13 11:16:54 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.12:9007", host: "symfony"
2022/09/13 11:16:54 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.12:9007", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:16:54 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.14:9006", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:16:54 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:16:54 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.16:9004", host: "symfony", referrer: "https://symfony/"
2022/09/13 11:17:07 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.12:9007", host: "symfony.test.ru"
2022/09/13 11:17:07 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.14:9006", host: "symfony.test.ru"
2022/09/13 11:17:07 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "symfony.test.ru"
2022/09/13 11:17:07 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.16:9004", host: "symfony.test.ru"
2022/09/13 11:17:08 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.16:9004", host: "symfony.test.ru", referrer: "https://symfony.test.ru/"
2022/09/13 11:17:08 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "symfony.test.ru", referrer: "https://symfony.test.ru/"
2022/09/13 11:17:08 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.14:9006", host: "symfony.test.ru", referrer: "https://symfony.test.ru/"
2022/09/13 11:17:08 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.12:9007", host: "symfony.test.ru", referrer: "https://symfony.test.ru/"
2022/09/13 11:17:22 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.16:9004", host: "symfony.test.ru"
2022/09/13 11:17:22 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "symfony.test.ru"
2022/09/13 11:17:22 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.12:9007", host: "symfony.test.ru"
2022/09/13 11:17:22 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.14:9006", host: "symfony.test.ru"
2022/09/13 11:17:23 [error] 7#7: *15 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://highload-symfony", host: "symfony.test.ru", referrer: "https://symfony.test.ru/"
2022/09/13 11:17:25 [error] 7#7: *15 no live upstreams while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://highload-symfony", host: "symfony.test.ru"
2022/09/13 11:17:26 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.14:9006", host: "symfony.test.ru", referrer: "https://symfony.test.ru/"
2022/09/13 11:17:26 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.12:9007", host: "symfony.test.ru", referrer: "https://symfony.test.ru/"
2022/09/13 11:17:26 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "symfony.test.ru", referrer: "https://symfony.test.ru/"
2022/09/13 11:17:26 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.16:9004", host: "symfony.test.ru", referrer: "https://symfony.test.ru/"
2022/09/13 11:18:15 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.14:9006", host: "symfony"
2022/09/13 11:18:15 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.12:9007", host: "symfony"
2022/09/13 11:18:15 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9005", host: "symfony"
2022/09/13 11:18:15 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.16:9004", host: "symfony"
